### ISSUE TITLE
RawData EIP712

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/hermezjs#167]
## Issue
- EIP712 is not yet supported by hardware wallets

## Solution
- Retrieve hash message from EIP712 data type and sign in with `signer.signMessage(message)`

## Info collected
- ethers abstract class for private key: https://github.com/ethers-io/ethers.js/blob/ce8f1e4015c0f27bf178238770b1325136e3351a/packages/wallet/src.ts/index.ts
- ethers abstarct class for JSONRpcProvider: https://github.com/ethers-io/ethers.js/blob/ce8f1e4015c0f27bf178238770b1325136e3351a/packages/providers/src.ts/json-rpc-provider.ts
- ethers encode EIP712 class: https://github.com/ethers-io/ethers.js/blob/ce8f1e4015c0f27bf178238770b1325136e3351a/packages/hash/src.ts/typed-data.ts
- more useful links:
  - example EIP712 ethereum: https://github.com/ethereum/EIPs/blob/master/assets/eip-712/Example.js
  - another example: https://codingturtles.com/?p=1562
- raw eip712 has for signer loaded with private keys could be found here: https://github.com/hermeznetwork/commonjs/blob/feature/raw-eip712/src/tx-utils.js#L468

**Comment by AlbertoElias** [comment]
@krlosMata can we close this at this point? It seems like we won't support it

**Comment by krlosMata** [comment]
Signing raw data is not possible with current libraries since it is not safe from user perspective given that any kind of transaction would be possible to sign, even malicious ones. Therefore it will not be implemented.
