### ISSUE TITLE
Can't clone integration-testing.git

### ISSUE THREAD

**Issue by aet00** [hermeznetwork/hermezjs#93]
> git clone https://github.com/hermeznetwork/integration-testing.git
Looks like it's not public?

I got failure: (node:13751) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8086
I suppose I should clone integration-testing.git and deploy a local setup ?

**Comment by AlbertoElias** [comment]
Hi, this is now fixed and that repo is no longer necessary! Sorry for the late reply and troubles
